package com.batman.upms.dao.mapper;

import com.batman.upms.dao.model.UpmsUserOrganization;
import com.batman.upms.dao.model.UpmsUserOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsUserOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    long countByExample(UpmsUserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int deleteByExample(UpmsUserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer userOrganizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int insert(UpmsUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int insertSelective(UpmsUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    List<UpmsUserOrganization> selectByExample(UpmsUserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    UpmsUserOrganization selectByPrimaryKey(Integer userOrganizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpmsUserOrganization record, @Param("example") UpmsUserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int updateByExample(@Param("record") UpmsUserOrganization record, @Param("example") UpmsUserOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(UpmsUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    int updateByPrimaryKey(UpmsUserOrganization record);
}