package com.batman.upms.dao.mapper;

import com.batman.upms.dao.model.UpmsSystemPermission;
import com.batman.upms.dao.model.UpmsSystemPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsSystemPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    long countByExample(UpmsSystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int deleteByExample(UpmsSystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int insert(UpmsSystemPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int insertSelective(UpmsSystemPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    List<UpmsSystemPermission> selectByExample(UpmsSystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    UpmsSystemPermission selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpmsSystemPermission record, @Param("example") UpmsSystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int updateByExample(@Param("record") UpmsSystemPermission record, @Param("example") UpmsSystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int updateByPrimaryKeySelective(UpmsSystemPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system_permission
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    int updateByPrimaryKey(UpmsSystemPermission record);
}