package com.batman.upms.dao.mapper;

import com.batman.upms.dao.model.UpmsOrganizationUser;
import com.batman.upms.dao.model.UpmsOrganizationUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsOrganizationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    long countByExample(UpmsOrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int deleteByExample(UpmsOrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int insert(UpmsOrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int insertSelective(UpmsOrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    List<UpmsOrganizationUser> selectByExample(UpmsOrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    UpmsOrganizationUser selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpmsOrganizationUser record, @Param("example") UpmsOrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int updateByExample(@Param("record") UpmsOrganizationUser record, @Param("example") UpmsOrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int updateByPrimaryKeySelective(UpmsOrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization_user
     *
     * @mbg.generated Fri Aug 04 16:20:04 CST 2017
     */
    int updateByPrimaryKey(UpmsOrganizationUser record);
}