package com.batman.upms.dao.mapper;

import com.batman.upms.dao.model.UpmsSystem;
import com.batman.upms.dao.model.UpmsSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    long countByExample(UpmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int deleteByExample(UpmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int insert(UpmsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int insertSelective(UpmsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    List<UpmsSystem> selectByExample(UpmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    UpmsSystem selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpmsSystem record, @Param("example") UpmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByExample(@Param("record") UpmsSystem record, @Param("example") UpmsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByPrimaryKeySelective(UpmsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByPrimaryKey(UpmsSystem record);
}