package com.batman.upms.dao.mapper;

import com.batman.upms.dao.model.UpmsLog;
import com.batman.upms.dao.model.UpmsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    long countByExample(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int deleteByExample(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int insert(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int insertSelective(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    List<UpmsLog> selectByExample(UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    UpmsLog selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpmsLog record, @Param("example") UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByExample(@Param("record") UpmsLog record, @Param("example") UpmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByPrimaryKeySelective(UpmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    int updateByPrimaryKey(UpmsLog record);
}