package com.batman.upms.dao.mapper;

import com.batman.upms.dao.model.UpmsUserRole;
import com.batman.upms.dao.model.UpmsUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    long countByExample(UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int deleteByExample(UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int insert(UpmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int insertSelective(UpmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    List<UpmsUserRole> selectByExample(UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    UpmsUserRole selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpmsUserRole record, @Param("example") UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int updateByExample(@Param("record") UpmsUserRole record, @Param("example") UpmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int updateByPrimaryKeySelective(UpmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_role
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    int updateByPrimaryKey(UpmsUserRole record);
}