package com.batman.upms.dao.model;

import java.io.Serializable;

public class UpmsLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.uuid
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.basepath
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String basepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.ip
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.function
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String function;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.spendtime
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String spendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.starttime
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.url
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.uri
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.username
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.result
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_log.deleteflag
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.uuid
     *
     * @return the value of upms_log.uuid
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.uuid
     *
     * @param uuid the value for upms_log.uuid
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.basepath
     *
     * @return the value of upms_log.basepath
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getBasepath() {
        return basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.basepath
     *
     * @param basepath the value for upms_log.basepath
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setBasepath(String basepath) {
        this.basepath = basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.ip
     *
     * @return the value of upms_log.ip
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.ip
     *
     * @param ip the value for upms_log.ip
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.function
     *
     * @return the value of upms_log.function
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.function
     *
     * @param function the value for upms_log.function
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setFunction(String function) {
        this.function = function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.spendtime
     *
     * @return the value of upms_log.spendtime
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getSpendtime() {
        return spendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.spendtime
     *
     * @param spendtime the value for upms_log.spendtime
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setSpendtime(String spendtime) {
        this.spendtime = spendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.starttime
     *
     * @return the value of upms_log.starttime
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.starttime
     *
     * @param starttime the value for upms_log.starttime
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.url
     *
     * @return the value of upms_log.url
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.url
     *
     * @param url the value for upms_log.url
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.uri
     *
     * @return the value of upms_log.uri
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.uri
     *
     * @param uri the value for upms_log.uri
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.username
     *
     * @return the value of upms_log.username
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.username
     *
     * @param username the value for upms_log.username
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.result
     *
     * @return the value of upms_log.result
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.result
     *
     * @param result the value for upms_log.result
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_log.deleteflag
     *
     * @return the value of upms_log.deleteflag
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_log.deleteflag
     *
     * @param deleteflag the value for upms_log.deleteflag
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", basepath=").append(basepath);
        sb.append(", ip=").append(ip);
        sb.append(", function=").append(function);
        sb.append(", spendtime=").append(spendtime);
        sb.append(", starttime=").append(starttime);
        sb.append(", url=").append(url);
        sb.append(", uri=").append(uri);
        sb.append(", username=").append(username);
        sb.append(", result=").append(result);
        sb.append(", deleteflag=").append(deleteflag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsLog other = (UpmsLog) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getBasepath() == null ? other.getBasepath() == null : this.getBasepath().equals(other.getBasepath()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getFunction() == null ? other.getFunction() == null : this.getFunction().equals(other.getFunction()))
            && (this.getSpendtime() == null ? other.getSpendtime() == null : this.getSpendtime().equals(other.getSpendtime()))
            && (this.getStarttime() == null ? other.getStarttime() == null : this.getStarttime().equals(other.getStarttime()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getUri() == null ? other.getUri() == null : this.getUri().equals(other.getUri()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getDeleteflag() == null ? other.getDeleteflag() == null : this.getDeleteflag().equals(other.getDeleteflag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_log
     *
     * @mbg.generated Wed Aug 09 15:48:31 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getBasepath() == null) ? 0 : getBasepath().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getFunction() == null) ? 0 : getFunction().hashCode());
        result = prime * result + ((getSpendtime() == null) ? 0 : getSpendtime().hashCode());
        result = prime * result + ((getStarttime() == null) ? 0 : getStarttime().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getUri() == null) ? 0 : getUri().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getDeleteflag() == null) ? 0 : getDeleteflag().hashCode());
        return result;
    }
}