package com.batman.upms.dao.model;

public class UpmsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.uuid
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.username
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.password
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.realname
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    private String realname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.uuid
     *
     * @return the value of upms_user.uuid
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.uuid
     *
     * @param uuid the value for upms_user.uuid
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.username
     *
     * @return the value of upms_user.username
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.username
     *
     * @param username the value for upms_user.username
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.password
     *
     * @return the value of upms_user.password
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.password
     *
     * @param password the value for upms_user.password
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.realname
     *
     * @return the value of upms_user.realname
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.realname
     *
     * @param realname the value for upms_user.realname
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", realname=").append(realname);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsUser other = (UpmsUser) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Mon Jul 31 17:06:11 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        return result;
    }
}