package com.batman.upms.dao.model;

import java.util.Date;

public class UpmsSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.uuid
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.id
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.basepath
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String basepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.name
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.description
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.title
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.orders
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private Integer orders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.status
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.createtime
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.icon
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.banner
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String banner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.theme
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.deleteflag
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.uuid
     *
     * @return the value of upms_system.uuid
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.uuid
     *
     * @param uuid the value for upms_system.uuid
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.id
     *
     * @return the value of upms_system.id
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.id
     *
     * @param id the value for upms_system.id
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.basepath
     *
     * @return the value of upms_system.basepath
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getBasepath() {
        return basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.basepath
     *
     * @param basepath the value for upms_system.basepath
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setBasepath(String basepath) {
        this.basepath = basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.name
     *
     * @return the value of upms_system.name
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.name
     *
     * @param name the value for upms_system.name
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.description
     *
     * @return the value of upms_system.description
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.description
     *
     * @param description the value for upms_system.description
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.title
     *
     * @return the value of upms_system.title
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.title
     *
     * @param title the value for upms_system.title
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.orders
     *
     * @return the value of upms_system.orders
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.orders
     *
     * @param orders the value for upms_system.orders
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.status
     *
     * @return the value of upms_system.status
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.status
     *
     * @param status the value for upms_system.status
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.createtime
     *
     * @return the value of upms_system.createtime
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.createtime
     *
     * @param createtime the value for upms_system.createtime
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.icon
     *
     * @return the value of upms_system.icon
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.icon
     *
     * @param icon the value for upms_system.icon
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.banner
     *
     * @return the value of upms_system.banner
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.banner
     *
     * @param banner the value for upms_system.banner
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setBanner(String banner) {
        this.banner = banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.theme
     *
     * @return the value of upms_system.theme
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.theme
     *
     * @param theme the value for upms_system.theme
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.deleteflag
     *
     * @return the value of upms_system.deleteflag
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.deleteflag
     *
     * @param deleteflag the value for upms_system.deleteflag
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", id=").append(id);
        sb.append(", basepath=").append(basepath);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", title=").append(title);
        sb.append(", orders=").append(orders);
        sb.append(", status=").append(status);
        sb.append(", createtime=").append(createtime);
        sb.append(", icon=").append(icon);
        sb.append(", banner=").append(banner);
        sb.append(", theme=").append(theme);
        sb.append(", deleteflag=").append(deleteflag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsSystem other = (UpmsSystem) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBasepath() == null ? other.getBasepath() == null : this.getBasepath().equals(other.getBasepath()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getOrders() == null ? other.getOrders() == null : this.getOrders().equals(other.getOrders()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getBanner() == null ? other.getBanner() == null : this.getBanner().equals(other.getBanner()))
            && (this.getTheme() == null ? other.getTheme() == null : this.getTheme().equals(other.getTheme()))
            && (this.getDeleteflag() == null ? other.getDeleteflag() == null : this.getDeleteflag().equals(other.getDeleteflag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Wed Aug 09 13:12:47 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBasepath() == null) ? 0 : getBasepath().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getOrders() == null) ? 0 : getOrders().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getBanner() == null) ? 0 : getBanner().hashCode());
        result = prime * result + ((getTheme() == null) ? 0 : getTheme().hashCode());
        result = prime * result + ((getDeleteflag() == null) ? 0 : getDeleteflag().hashCode());
        return result;
    }
}