package com.batman.upms.dao.model;

public class UpmsPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.permission_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.system_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.pid
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.type
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.permission_value
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String permissionValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.uri
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.icon
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.status
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.orders
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Long orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.permission_id
     *
     * @return the value of upms_permission.permission_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.permission_id
     *
     * @param permissionId the value for upms_permission.permission_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.system_id
     *
     * @return the value of upms_permission.system_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.system_id
     *
     * @param systemId the value for upms_permission.system_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.pid
     *
     * @return the value of upms_permission.pid
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.pid
     *
     * @param pid the value for upms_permission.pid
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.name
     *
     * @return the value of upms_permission.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.name
     *
     * @param name the value for upms_permission.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.type
     *
     * @return the value of upms_permission.type
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.type
     *
     * @param type the value for upms_permission.type
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.permission_value
     *
     * @return the value of upms_permission.permission_value
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getPermissionValue() {
        return permissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.permission_value
     *
     * @param permissionValue the value for upms_permission.permission_value
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setPermissionValue(String permissionValue) {
        this.permissionValue = permissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.uri
     *
     * @return the value of upms_permission.uri
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.uri
     *
     * @param uri the value for upms_permission.uri
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.icon
     *
     * @return the value of upms_permission.icon
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.icon
     *
     * @param icon the value for upms_permission.icon
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.status
     *
     * @return the value of upms_permission.status
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.status
     *
     * @param status the value for upms_permission.status
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.ctime
     *
     * @return the value of upms_permission.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.ctime
     *
     * @param ctime the value for upms_permission.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.orders
     *
     * @return the value of upms_permission.orders
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Long getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.orders
     *
     * @param orders the value for upms_permission.orders
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setOrders(Long orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionId=").append(permissionId);
        sb.append(", systemId=").append(systemId);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", permissionValue=").append(permissionValue);
        sb.append(", uri=").append(uri);
        sb.append(", icon=").append(icon);
        sb.append(", status=").append(status);
        sb.append(", ctime=").append(ctime);
        sb.append(", orders=").append(orders);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsPermission other = (UpmsPermission) that;
        return (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getSystemId() == null ? other.getSystemId() == null : this.getSystemId().equals(other.getSystemId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPermissionValue() == null ? other.getPermissionValue() == null : this.getPermissionValue().equals(other.getPermissionValue()))
            && (this.getUri() == null ? other.getUri() == null : this.getUri().equals(other.getUri()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getOrders() == null ? other.getOrders() == null : this.getOrders().equals(other.getOrders()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getSystemId() == null) ? 0 : getSystemId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPermissionValue() == null) ? 0 : getPermissionValue().hashCode());
        result = prime * result + ((getUri() == null) ? 0 : getUri().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getOrders() == null) ? 0 : getOrders().hashCode());
        return result;
    }
}