package com.batman.upms.dao.model;

public class UpmsOrganization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_organization.organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_organization.pid
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_organization.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_organization.description
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_organization.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Long ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_organization.organization_id
     *
     * @return the value of upms_organization.organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_organization.organization_id
     *
     * @param organizationId the value for upms_organization.organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_organization.pid
     *
     * @return the value of upms_organization.pid
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_organization.pid
     *
     * @param pid the value for upms_organization.pid
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_organization.name
     *
     * @return the value of upms_organization.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_organization.name
     *
     * @param name the value for upms_organization.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_organization.description
     *
     * @return the value of upms_organization.description
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_organization.description
     *
     * @param description the value for upms_organization.description
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_organization.ctime
     *
     * @return the value of upms_organization.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_organization.ctime
     *
     * @param ctime the value for upms_organization.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", organizationId=").append(organizationId);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsOrganization other = (UpmsOrganization) that;
        return (this.getOrganizationId() == null ? other.getOrganizationId() == null : this.getOrganizationId().equals(other.getOrganizationId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_organization
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrganizationId() == null) ? 0 : getOrganizationId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        return result;
    }
}