package com.batman.upms.dao.model;

public class UpmsSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.system_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.icon
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.banner
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String banner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.theme
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.basepath
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String basepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.status
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.title
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.description
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_system.orders
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Long orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.system_id
     *
     * @return the value of upms_system.system_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.system_id
     *
     * @param systemId the value for upms_system.system_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.icon
     *
     * @return the value of upms_system.icon
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.icon
     *
     * @param icon the value for upms_system.icon
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.banner
     *
     * @return the value of upms_system.banner
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.banner
     *
     * @param banner the value for upms_system.banner
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setBanner(String banner) {
        this.banner = banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.theme
     *
     * @return the value of upms_system.theme
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.theme
     *
     * @param theme the value for upms_system.theme
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.basepath
     *
     * @return the value of upms_system.basepath
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getBasepath() {
        return basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.basepath
     *
     * @param basepath the value for upms_system.basepath
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setBasepath(String basepath) {
        this.basepath = basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.status
     *
     * @return the value of upms_system.status
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.status
     *
     * @param status the value for upms_system.status
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.name
     *
     * @return the value of upms_system.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.name
     *
     * @param name the value for upms_system.name
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.title
     *
     * @return the value of upms_system.title
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.title
     *
     * @param title the value for upms_system.title
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.description
     *
     * @return the value of upms_system.description
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.description
     *
     * @param description the value for upms_system.description
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.ctime
     *
     * @return the value of upms_system.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.ctime
     *
     * @param ctime the value for upms_system.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_system.orders
     *
     * @return the value of upms_system.orders
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Long getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_system.orders
     *
     * @param orders the value for upms_system.orders
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setOrders(Long orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", systemId=").append(systemId);
        sb.append(", icon=").append(icon);
        sb.append(", banner=").append(banner);
        sb.append(", theme=").append(theme);
        sb.append(", basepath=").append(basepath);
        sb.append(", status=").append(status);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", ctime=").append(ctime);
        sb.append(", orders=").append(orders);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsSystem other = (UpmsSystem) that;
        return (this.getSystemId() == null ? other.getSystemId() == null : this.getSystemId().equals(other.getSystemId()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getBanner() == null ? other.getBanner() == null : this.getBanner().equals(other.getBanner()))
            && (this.getTheme() == null ? other.getTheme() == null : this.getTheme().equals(other.getTheme()))
            && (this.getBasepath() == null ? other.getBasepath() == null : this.getBasepath().equals(other.getBasepath()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getOrders() == null ? other.getOrders() == null : this.getOrders().equals(other.getOrders()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_system
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSystemId() == null) ? 0 : getSystemId().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getBanner() == null) ? 0 : getBanner().hashCode());
        result = prime * result + ((getTheme() == null) ? 0 : getTheme().hashCode());
        result = prime * result + ((getBasepath() == null) ? 0 : getBasepath().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getOrders() == null) ? 0 : getOrders().hashCode());
        return result;
    }
}