package com.batman.upms.dao.model;

public class UpmsUserPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_permission.user_permission_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Integer userPermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_permission.user_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_permission.permission_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_permission.type
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_permission.user_permission_id
     *
     * @return the value of upms_user_permission.user_permission_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Integer getUserPermissionId() {
        return userPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_permission.user_permission_id
     *
     * @param userPermissionId the value for upms_user_permission.user_permission_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setUserPermissionId(Integer userPermissionId) {
        this.userPermissionId = userPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_permission.user_id
     *
     * @return the value of upms_user_permission.user_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_permission.user_id
     *
     * @param userId the value for upms_user_permission.user_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_permission.permission_id
     *
     * @return the value of upms_user_permission.permission_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_permission.permission_id
     *
     * @param permissionId the value for upms_user_permission.permission_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_permission.type
     *
     * @return the value of upms_user_permission.type
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_permission.type
     *
     * @param type the value for upms_user_permission.type
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_permission
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userPermissionId=").append(userPermissionId);
        sb.append(", userId=").append(userId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_permission
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsUserPermission other = (UpmsUserPermission) that;
        return (this.getUserPermissionId() == null ? other.getUserPermissionId() == null : this.getUserPermissionId().equals(other.getUserPermissionId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_permission
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserPermissionId() == null) ? 0 : getUserPermissionId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }
}