package com.batman.upms.dao.model;

public class UpmsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.user_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.username
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.password
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.salt
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.realname
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.avatar
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.phone
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.email
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.sex
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.locked
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Byte locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Long ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.user_id
     *
     * @return the value of upms_user.user_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.user_id
     *
     * @param userId the value for upms_user.user_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.username
     *
     * @return the value of upms_user.username
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.username
     *
     * @param username the value for upms_user.username
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.password
     *
     * @return the value of upms_user.password
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.password
     *
     * @param password the value for upms_user.password
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.salt
     *
     * @return the value of upms_user.salt
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.salt
     *
     * @param salt the value for upms_user.salt
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.realname
     *
     * @return the value of upms_user.realname
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.realname
     *
     * @param realname the value for upms_user.realname
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.avatar
     *
     * @return the value of upms_user.avatar
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.avatar
     *
     * @param avatar the value for upms_user.avatar
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.phone
     *
     * @return the value of upms_user.phone
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.phone
     *
     * @param phone the value for upms_user.phone
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.email
     *
     * @return the value of upms_user.email
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.email
     *
     * @param email the value for upms_user.email
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.sex
     *
     * @return the value of upms_user.sex
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.sex
     *
     * @param sex the value for upms_user.sex
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.locked
     *
     * @return the value of upms_user.locked
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.locked
     *
     * @param locked the value for upms_user.locked
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user.ctime
     *
     * @return the value of upms_user.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user.ctime
     *
     * @param ctime the value for upms_user.ctime
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", realname=").append(realname);
        sb.append(", avatar=").append(avatar);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", sex=").append(sex);
        sb.append(", locked=").append(locked);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsUser other = (UpmsUser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getLocked() == null ? other.getLocked() == null : this.getLocked().equals(other.getLocked()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getLocked() == null) ? 0 : getLocked().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        return result;
    }
}