package com.batman.upms.dao.model;

public class UpmsPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.uuid
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.id
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.name
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.permission_type
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    private Byte permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.permission_info
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    private String permissionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_permission.deleteflag
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.uuid
     *
     * @return the value of upms_permission.uuid
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.uuid
     *
     * @param uuid the value for upms_permission.uuid
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.id
     *
     * @return the value of upms_permission.id
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.id
     *
     * @param id the value for upms_permission.id
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.name
     *
     * @return the value of upms_permission.name
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.name
     *
     * @param name the value for upms_permission.name
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.permission_type
     *
     * @return the value of upms_permission.permission_type
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public Byte getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.permission_type
     *
     * @param permissionType the value for upms_permission.permission_type
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public void setPermissionType(Byte permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.permission_info
     *
     * @return the value of upms_permission.permission_info
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public String getPermissionInfo() {
        return permissionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.permission_info
     *
     * @param permissionInfo the value for upms_permission.permission_info
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public void setPermissionInfo(String permissionInfo) {
        this.permissionInfo = permissionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_permission.deleteflag
     *
     * @return the value of upms_permission.deleteflag
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_permission.deleteflag
     *
     * @param deleteflag the value for upms_permission.deleteflag
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", permissionType=").append(permissionType);
        sb.append(", permissionInfo=").append(permissionInfo);
        sb.append(", deleteflag=").append(deleteflag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsPermission other = (UpmsPermission) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPermissionType() == null ? other.getPermissionType() == null : this.getPermissionType().equals(other.getPermissionType()))
            && (this.getPermissionInfo() == null ? other.getPermissionInfo() == null : this.getPermissionInfo().equals(other.getPermissionInfo()))
            && (this.getDeleteflag() == null ? other.getDeleteflag() == null : this.getDeleteflag().equals(other.getDeleteflag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_permission
     *
     * @mbg.generated Fri Aug 04 11:24:06 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPermissionType() == null) ? 0 : getPermissionType().hashCode());
        result = prime * result + ((getPermissionInfo() == null) ? 0 : getPermissionInfo().hashCode());
        result = prime * result + ((getDeleteflag() == null) ? 0 : getDeleteflag().hashCode());
        return result;
    }
}