package com.batman.upms.dao.model;

public class UpmsUserOrganization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_organization.user_organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer userOrganizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_organization.user_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_user_organization.organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    private Integer organizationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_organization.user_organization_id
     *
     * @return the value of upms_user_organization.user_organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getUserOrganizationId() {
        return userOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_organization.user_organization_id
     *
     * @param userOrganizationId the value for upms_user_organization.user_organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setUserOrganizationId(Integer userOrganizationId) {
        this.userOrganizationId = userOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_organization.user_id
     *
     * @return the value of upms_user_organization.user_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_organization.user_id
     *
     * @param userId the value for upms_user_organization.user_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_user_organization.organization_id
     *
     * @return the value of upms_user_organization.organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_user_organization.organization_id
     *
     * @param organizationId the value for upms_user_organization.organization_id
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userOrganizationId=").append(userOrganizationId);
        sb.append(", userId=").append(userId);
        sb.append(", organizationId=").append(organizationId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsUserOrganization other = (UpmsUserOrganization) that;
        return (this.getUserOrganizationId() == null ? other.getUserOrganizationId() == null : this.getUserOrganizationId().equals(other.getUserOrganizationId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrganizationId() == null ? other.getOrganizationId() == null : this.getOrganizationId().equals(other.getOrganizationId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user_organization
     *
     * @mbg.generated Mon Jul 31 14:37:12 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserOrganizationId() == null) ? 0 : getUserOrganizationId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrganizationId() == null) ? 0 : getOrganizationId().hashCode());
        return result;
    }
}