package com.batman.upms.dao.model;

public class UpmsRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.role_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.name
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.title
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.description
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.ctime
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upms_role.orders
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    private Long orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.role_id
     *
     * @return the value of upms_role.role_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.role_id
     *
     * @param roleId the value for upms_role.role_id
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.name
     *
     * @return the value of upms_role.name
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.name
     *
     * @param name the value for upms_role.name
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.title
     *
     * @return the value of upms_role.title
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.title
     *
     * @param title the value for upms_role.title
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.description
     *
     * @return the value of upms_role.description
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.description
     *
     * @param description the value for upms_role.description
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.ctime
     *
     * @return the value of upms_role.ctime
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.ctime
     *
     * @param ctime the value for upms_role.ctime
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upms_role.orders
     *
     * @return the value of upms_role.orders
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public Long getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upms_role.orders
     *
     * @param orders the value for upms_role.orders
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    public void setOrders(Long orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", ctime=").append(ctime);
        sb.append(", orders=").append(orders);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpmsRole other = (UpmsRole) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getOrders() == null ? other.getOrders() == null : this.getOrders().equals(other.getOrders()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_role
     *
     * @mbg.generated Mon Jul 31 14:29:20 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getOrders() == null) ? 0 : getOrders().hashCode());
        return result;
    }
}